CREATE TABLE IF NOT EXISTS post (
    id SERIAL PRIMARY KEY NOT NULL,
    parent_id INT REFERENCES post(id),
    text VARCHAR(255) NOT NULL,
    likes INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);